server:
  port: 18081

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址

spring:
  application:
    name: shabao-oss-cloud
  profiles:
    active: native #设置再本地的 resources目录下读取文件
  #开启当前安全认证后，需要密码才能链接配置中心  
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 123
  
    
